### ISSUE TITLE
Get API Credential - Back End

### ISSUE THREAD

**Issue by leonmex** [mailchimp/mc-magento#179]
Hello guys,

I just start to test the last  version 1.1.5 of your module in magento 1.9.3.1 CE and when in the backend  want to *Get API Credentials* after login to mailchimp account and select my account always return one error:

*Unable to retrieve the token*
*This likely means that a timeout happended and the token is not available.*
*Please close this window and try again.*

And i think is because the first call to login into mailchimp account is the url:

https://login.mailchimp.com/oauth2/authorize?redirect_uri=https%3A%2F%2Febizmarts.com%2Fmagento%2F*mc-magento*%2Foauth2%2Fcomplete.php&response_type=code&client_id=

with the *mc-magento* and not mailchimp 

best.

**Comment by Santiagoebizmarts** [comment]
Hello @leonmex 
We will take a look into this as soon as possible. When we find the solution this issue will be referenced.

Thanks for your feedback!

Regards.

**Comment by ebizmarts-keller** [comment]
Just for feedback: I can confirm this has happened to me consistently with version 1.1.6 (even with a new clean installation)

**Comment by ebizmarts-keller** [comment]
Hello @leonmex 

It seems this was a problem with our server, it has been corrected now, please test it now.

**Comment by soimudaniel** [comment]
Hello @ebizmarts-keller. We are using v 1.1.5 on our magento 1.9 CE version, and we get the: Unable to retrieve the token

This likely means that a timeout happended and the token is not available.

Please close this window and try again.

error too. It worked until 2 or 3 days ago and suddenly stop working. 
Please get back to us as soon as possible. Thank you

**Comment by Santiagoebizmarts** [comment]
Hello,

We are looking to solve this problem.
In the meantime you can find your MailChimp APi keys as explained [here](http://kb.mailchimp.com/integrations/api-integrations/about-api-keys).

Regards.

**Comment by leonmex** [comment]
Thanks @Santiagoebizmarts

**Comment by ToonSpinISAAC** [comment]
Still getting the error in version 1.1.6. Is the fix for this in version 1.1.6? Because the fact that you added the 1.1.7 milestone to this issue seems to indicate that it isn't.

**Comment by ToonSpinISAAC** [comment]
It's working again now, so probably a server thing or something after all, but it quite clearly isn't a timeout so I would suggest changing the error message.

Maybe a help message explaining how to manually get the API key (it's not actually that difficult if you know where to look) would be a good idea.
